# Email from Director Summers

From: Evelyn Summers  <Eveyln.Summers@gotham.gov>  
Sent: Saturday, August 17, 2024, 10:50AM  
To: Me  
Subject: FW: Program Improvement and Funding 

See below. Can you pull that together for me? Use 2021 and 2022 data. Gov meets with his cabinet on Monday morning at 7:30 a.m.  

***
 
From: Chuck Thompson <Chuck.thompson@gotham.gov>  
Sent: Saturday, August 17, 2024, 10:37AM  
To: Evelyn Summers <Evelyn.Summers@gdoc.gov>  
Subject: Program Improvement and Funding 

Firebrand, 

As we discussed over the phone, I’m getting a lot of pressure from the legislature due to the Center Wing Coalition report. Appreciate the efforts from your team to pull together updated numbers to match the programs they wanted to see.  

I think CWC understands the concept of weighted averages, but they are now saying that the data is old.  

Can we update the reports with the latest data? I will talk to them again directly after cabinet, so Monday morning would be great.  

Give Tommy my best! 

Chuck "Go-Getter" Thompson  
The Best Governor of Gotham  