# Welcome

As part of an ongoing staffing crisis, you have been asked by your director to reproduce a report that was produced under the last research director, who is now on a beach, enjoying her retirement, and unreachable. You asked your only analyst to try to reproduce the report, but they have not yet been able to, and there doesn’t seem to be any record of how the numbers were produced. The report establishes recidivism rates for several key programs and provides staffing levels for those programs. Your director wants to make the case that the DOC needs staff to implement successful programs. This is in response to a group of hostile legislators (a mix of far-right fiscal conservatives who do not believe in prison programs and far-left “de-funders” who think your budget is too big). They are running a bill to reduce your overall budget and eliminate some existing staff vacancies, with the argument that if you have survived for the past two years with your current staffing levels, you must be doing okay.

## Case Study Narrative

### [Scenario](va_cs.html)

Amidst a swirling staffing crisis at the Gotham Department of Corrections (GDOC), you find yourself in a peculiar predicament. Your director, the fearsome Evelyn "Firebrand" Summers, has thrust upon you the Herculean task of resurrecting a report forged under the previous Research Director Miranda "Mermaid" Shelsky. Dr. Shelsky, now retired and sipping mojitos on a secluded beach in Fiji, left behind a report detailing recidivism rates and the indispensable staffing needs for DOC's prized programs. 

The report establishes recidivism rates for several key supervision/reentry programs for high risk people and provides staffing levels for these programs. Director Summers is depending on you to build a case to keep the necessary staff to implement these programs successfully.  

You ask your only analyst to try to reproduce the report, yet there mysteriously doesn’t seem to be any record of how the original report’s numbers were produced. Your analyst has spent 3 days and cannot seem to figure out the formula. The analyst is also now 3 days behind on other tasks that have been assigned and it is time to move on.  

Meanwhile, the ever-persistent Center Wing Coalition (CWC) are crafting a bill to counteract all of the progress your agency has been making in your recidivism-reduction efforts. The CWC argue that, if your agency has survived for the past two years with current staffing levels, you must be doing okay and are advocating to cut your overall allocated FTE. Meanwhile, your staff is working overtime through lunch, and you are certain you saw at least two team members browsing on Indeed last week. 

You’re in a tight bind, and time is ticking. Not to mention, your best friend has planned a getaway next month in Las Vegas. You paid for this trip over six months ago and you have no intention of missing it. However, you have no desire to be sitting in the Blue Man Group show thinking about this data…  

## About Virtual Academy

The Advancing Data in Corrections initiative includes a [Virtual Academy](https://advancingdataincorrections.org/va), which builds data literacy and analytic capabilities within departments of corrections nationwide to further data-informed planning and decision-making. Through their participation in the Virtual Academy, corrections agency staff can access the program’s self-paced learning materials, community forum, peer-to-peer networks, and technical assistance at no cost.

For more information about the program and the tools, services, and opportunies available, visit the [Virtual Academy website](https://advancingdataincorrections.org/va).