# Old GDOC Report 

## Recidivism and Staffing Requirements for Programs, January 2018

This report includes the one-year recidivism rates for evidence-based programming provided in the Gotham Department of Corrections facilities for high-risk people. Staffing numbers describe how many full-time employees are needed over the course of a year to keep each program running. Each program facilitator completes extensive training and must complete eight hours of continuing education each year.

```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(kableExtra)
library(dplyr)
data.frame(pgm   = c("Anger Management",
                     "The Bureau Rehabilitation and Values Enhancement Program",
                     "Basic Cognitive Skills",
                     "The Resolve Program",
                     "Residential Drug Abuse Program",
                     "Dialectical Behavior Therapy",
                     "Sex Offender Treatment Program",
                     "Challenge Program", 
                     "Mental Health Step Down Program", 
                     "Steps Toward Awareness, Growth, and Emotional Strength Program"),
            recid = c(0.90, 0.38, 0.41, 0.59, 0.36, 0.57, 0.05, 0.44, 0.08, 0.92),
            stf   = c(2, 9, 4, 8, 5, 16, 11, 4, 7, 17)
) |> rename("Program (Graduated 2015)" = pgm,
            "Recidivism Rate (2016)" = recid,
            "Staffing" = stf) |>
  kbl()
```

<br />

## Findings
Overall, the programs that resulted in the lowest recidivism rates are the Mental Health Step Down Program and the Sex Offender Treatment Program. The programs that have the highest recidivism rates are Anger Management and Steps Toward Awareness, Growth, and Emotional Strength Program.

## Methodology
All participants have taken one of these programs right before release. The cohort analyzed were released from prison in 2016. One-year recidivism rates are computed.